"""Константы для проекта."""

CHARACTERS = ('abcdefghijklmnopqrs '
              'tuvwxyz0123456789')
CREATE_USER_MAX_LENGTH = 150
INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64
MIN_VALUE_VALIDATOR = 1
MAX_VALUE_VALIDATOR = 32_000
PAGE_SIZE = 6
RECIPE_NAME_MAX_LENGTH = 256
RECIPE_SHORT_URL_MAX_LENGTH = 10
TAG_MAX_LENGTH = 32
