# Generated by Django 3.2 on 2024-09-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'в избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'ингредиент в рецепт', 'verbose_name_plural': 'Ингредиенты добавленные в рецепт'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'в корзину', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'тег для рецепта', 'verbose_name_plural': 'Теги добавленные к рецепту'},
        ),
    ]
