# Generated by Django 3.2 on 2024-08-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240822_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes_image', verbose_name='Изображение'),
        ),
    ]
