# Generated by Django 3.2 on 2024-09-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createuser',
            options={'ordering': ('username',), 'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
